setTimeout(function() { // 为何会执行 单独执行里面的函数会报错
  console.log(1)
}, 100)
